apiVersion: v1
kind: Service
metadata:
  name: fact-checking-backend-service
  labels:
    app: fact-checking-backend
spec:
  selector:
    app: fact-checking-backend # Selects pods with this label
  ports:
    - protocol: TCP
      port: 8081 # The port the service will listen on (external port within the cluster)
      targetPort: 8081 # The port the container is listening on (internal port of the pod)
  type: NodePort # Exposes the service on a port on each node's IP. Good for local testing.
                 # For production, consider LoadBalancer (cloud providers) or Ingress.
