apiVersion: v1
kind: Service
metadata:
  name: fact-checking-frontend-service
  labels:
    app: fact-checking-frontend
spec:
  selector:
    app: fact-checking-frontend # Selects pods with this label
  ports:
    - protocol: TCP
      port: 80 # The port the service will listen on
      targetPort: 80 # The port the container is listening on
  type: NodePort # Exposes the service on a port on each node's IP.
