name: Backend CI/CD

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
    paths:
      - 'backend/**' # Only run if changes are detected in the backend folder
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch: # Allows manual triggering from GitHub UI

env:
  JAVA_VERSION: '17'
  SPRING_BOOT_APP_PATH: './backend'
  DOCKER_IMAGE_NAME: 'fact-checking-backend' # This is just the base name, not the full name
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Build Spring Boot Application
        run: mvn clean package -DskipTests
        working-directory: ${{ env.SPRING_BOOT_APP_PATH }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.SPRING_BOOT_APP_PATH }}
          push: true
          # Construct the full image tag directly here, using the env.DOCKER_IMAGE_NAME
          # IMPORTANT: REPLACE 'samscam18' WITH YOUR ACTUAL DOCKER HUB USERNAME
          tags: |
            samscam18/${{ env.DOCKER_IMAGE_NAME }}:latest
            samscam18/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
          platforms: linux/amd64

      - name: Verify Docker Image Push (Optional)
        run: |
          # IMPORTANT: REPLACE 'samscam18' WITH YOUR ACTUAL DOCKER HUB USERNAME
          echo "Docker image samscam18/${{ env.DOCKER_IMAGE_NAME }}:latest pushed successfully!"
          echo "You can view it on Docker Hub: https://hub.docker.com/r/samscam18/${{ env.DOCKER_IMAGE_NAME }}/tags"
