name: Backend CI/CD

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
    paths:
      - 'backend/**' # Only run if changes are detected in the backend folder
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch: # Allows manual triggering from GitHub UI

env:
  JAVA_VERSION: '17' # Specify your Java version
  SPRING_BOOT_APP_PATH: './backend' # Path to your Spring Boot application
  DOCKER_IMAGE_NAME: 'fact-checking-backend' # Name for your Docker image (keep this)
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }} # Your Docker Hub username from GitHub Secrets
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_PASSWORD }} # Your Docker Hub token from GitHub Secrets
  # Define DOCKER_IMAGE_FULL_NAME once, using your actual Docker Hub username directly
  # IMPORTANT: REPLACE 'samscam18' WITH YOUR ACTUAL DOCKER HUB USERNAME
  DOCKER_IMAGE_FULL_NAME: 'samscam18/fact-checking-backend' # <--- CORRECTED AND SINGLE DEFINITION

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Use a fresh Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin' # Recommended distribution
          cache: 'maven' # Cache Maven dependencies to speed up builds

      - name: Build Spring Boot Application
        run: mvn clean package -DskipTests # Build JAR, skipping tests for faster CI
        working-directory: ${{ env.SPRING_BOOT_APP_PATH }} # Run Maven in the backend directory

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.SPRING_BOOT_APP_PATH }} # Context for Docker build is the backend directory
          push: true # Push the image to Docker Hub
          tags: |
            ${{ env.DOCKER_IMAGE_FULL_NAME }}:latest
            ${{ env.DOCKER_IMAGE_FULL_NAME }}:${{ github.sha }} # Tag with commit SHA for unique versioning
          platforms: linux/amd64 # Specify platform for compatibility

      - name: Verify Docker Image Push (Optional)
        run: |
          echo "Docker image ${{ env.DOCKER_IMAGE_FULL_NAME }}:latest pushed successfully!"
          echo "You can view it on Docker Hub: https://hub.docker.com/r/${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}/tags"
