name: Frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
  workflow_dispatch:

env:
  FRONTEND_APP_PATH: './frontend'
  DOCKER_IMAGE_NAME: 'fact-checking-frontend' # Base image name
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.FRONTEND_APP_PATH }}
          push: true
          # Construct the full image tag directly here
          # IMPORTANT: REPLACE 'samscam18' WITH YOUR ACTUAL DOCKER HUB USERNAME
          tags: |
            samscam18/${{ env.DOCKER_IMAGE_NAME }}:latest
            samscam18/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
          platforms: linux/amd64

      - name: Verify Docker Image Push (Optional)
        run: |
          # IMPORTANT: REPLACE 'samscam18' WITH YOUR ACTUAL DOCKER HUB USERNAME
          echo "Docker image samscam18/${{ env.DOCKER_IMAGE_NAME }}:latest pushed successfully!"
          echo "You can view it on Docker Hub: https://hub.docker.com/r/samscam18/${{ env.DOCKER_IMAGE_NAME }}/tags"
